<a href="https://colab.research.google.com/github/ervaishnavisutar-del/ddaex/blob/main/engineering_feature_Ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import pandas as pd
import matplotlib.pyplot as plt

In [48]:
data={
    "Name":["Alex","Bob","Charlie","David","Ethon"],
    "Age":[22,26,35,40,33],
    "Salary":[22000,35000,45000,160000,40000],
    "City":["Mumbai","Pune","Mumbai","Miraj","miraj"]
}
df=pd.DataFrame(data)
df

      Name  Age  Salary    City
0     Alex   22   22000  Mumbai
1      Bob   26   35000    Pune
2  Charlie   35   45000  Mumbai
3    David   40  160000   Miraj
4    Ethon   33   40000   miraj

In [49]:
df["Age.Group"]=pd.cut(
    df["Age"],
    bins=[0,25,40,100],
    labels=["Young","Adult","Senior"]
)
df

      Name  Age  Salary    City Age.Group
0     Alex   22   22000  Mumbai     Young
1      Bob   26   35000    Pune     Adult
2  Charlie   35   45000  Mumbai     Adult
3    David   40  160000   Miraj     Adult
4    Ethon   33   40000   miraj     Adult

In [50]:
#Add Salary Category Feature
def Salary_Categories(Salary):
  if Salary<=35000:
      return"Low"
  elif Salary<=75000:
      return"Medium"
  else:
      return"High"
df ["Salary_Category"]= df["Salary"].apply(Salary_Categories)
df

      Name  Age  Salary    City Age.Group Salary_Category
0     Alex   22   22000  Mumbai     Young             Low
1      Bob   26   35000    Pune     Adult             Low
2  Charlie   35   45000  Mumbai     Adult          Medium
3    David   40  160000   Miraj     Adult            High
4    Ethon   33   40000   miraj     Adult          Medium

In [51]:
# One-Hot Encoding
City_encoded=pd.get_dummies(df["City"])
City_encoded

   Miraj  Mumbai   Pune  miraj
0  False    True  False  False
1  False   False   True  False
2  False    True  False  False
3   True   False  False  False
4  False   False  False   True

In [52]:
#Combing Data
df["Combined"]=df["Salary"]/df["Age"]
df["Combined"]

0    1000.000000
1    1346.153846
2    1285.714286
3    4000.000000
4    1212.121212
Name: Combined, dtype: float64

In [63]:
from sklearn.preprocessing import MinMaxScaler
Scalar=MinMaxScaler()
df["Age_Scaled"]=Scalar.fit_transform(df[["Age"]])
df["Salary_Scaled"]=Scalar.fit_transform(df[["Salary"]])
df

,Name,Age,Salary,City,Age.Group,Salary_Category,Combined,Age_Scaled,Salary_Scaled
0,Alex,22,22000,Mumbai,Young,Low,1000.000000,0.000000,0.000000
1,Bob,26,35000,Pune,Adult,Low,1346.153846,0.222222,0.094203
2,Charlie,35,45000,Mumbai,Adult,Medium,1285.714286,0.722222,0.166667
3,David,40,160000,Miraj,Adult,High,4000.000000,1.000000,1.000000
4,Ethon,33,40000,miraj,Adult,Medium,1212.121212,0.611111,0.130435

In [64]:
from sklearn.preprocessing import StandardScaler
Scalar=StandardScaler()
df["Age_Std"]=Scalar.fit_transform(df[["Age"]])
df["Salary_Std"]=Scalar.fit_transform(df[["Salary"]])
df

,Name,Age,Salary,City,Age.Group,Salary_Category,Combined,Age_Scaled,Salary_Scaled,Age_Std,Salary_Std
0,Alex,22,22000,Mumbai,Young,Low,1000.000000,0.000000,0.000000,-1.430532,-0.762133
1,Bob,26,35000,Pune,Adult,Low,1346.153846,0.222222,0.094203,-0.808562,-0.504119
2,Charlie,35,45000,Mumbai,Adult,Medium,1285.714286,0.722222,0.166667,0.590872,-0.305647
3,David,40,160000,Miraj,Adult,High,4000.000000,1.000000,1.000000,1.368335,1.976782
4,Ethon,33,40000,miraj,Adult,Medium,1212.121212,0.611111,0.130435,0.279887,-0.404883