<a href="https://colab.research.google.com/github/ervaishnavisutar-del/ddaex/blob/main/Medical_Insurance_Feature_Engineering%20Ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd
import numpy as np

In [33]:
df=pd.read_csv("medicalinsurance.csv")

In [34]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [35]:
df["age_group"]=pd.cut(
    df["age"],
    bins=[0,25,40,70],
    labels=["Young","Adult","Senior"]
)
df

      age     sex     bmi  children smoker     region      charges age_group
0      19  female  27.900         0    yes  southwest  16884.92400     Young
1      18    male  33.770         1     no  southeast   1725.55230     Young
2      28    male  33.000         3     no  southeast   4449.46200     Adult
3      33    male  22.705         0     no  northwest  21984.47061     Adult
4      32    male  28.880         0     no  northwest   3866.85520     Adult
...   ...     ...     ...       ...    ...        ...          ...       ...
1333   50    male  30.970         3     no  northwest  10600.54830    Senior
1334   18  female  31.920         0     no  northeast   2205.98080     Young
1335   18  female  36.850         0     no  southeast   1629.83350     Young
1336   21  female  25.800         0     no  southwest   2007.94500     Young
1337   61  female  29.070         0    yes  northwest  29141.36030    Senior

[1338 rows x 8 columns]

In [36]:
df["smoker_binary"]=df["sex"].map({"no":0,"yes":1})
df["sex_binary"]=df["sex"].map({"female":0,"male":1})
df

,age,sex,bmi,children,smoker,region,charges,age_group,smoker_binary,sex_binary
0,19,female,27.900,0,yes,southwest,16884.92400,Young,NaN,0
1,18,male,33.770,1,no,southeast,1725.55230,Young,NaN,1
2,28,male,33.000,3,no,southeast,4449.46200,Adult,NaN,1
3,33,male,22.705,0,no,northwest,21984.47061,Adult,NaN,1
4,32,male,28.880,0,no,northwest,3866.85520,Adult,NaN,1
...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Senior,NaN,1
1334,18,female,31.920,0,no,northeast,2205.98080,Young,NaN,0
1335,18,female,36.850,0,no,southeast,1629.83350,Young,NaN,0
1336,21,female,25.800,0,no,southwest,2007.94500,Young,NaN,0
1337,61,female,29.070,0,yes,northwest,29141.36030,Senior,NaN,0

In [37]:
df["bmi_category"]=pd.cut(
    df["bmi"],
    bins=[0,18,25,45],
    labels=["underweight","normal","overweight"]
)
df

,age,sex,bmi,children,smoker,region,charges,age_group,smoker_binary,sex_binary,bmi_category
0,19,female,27.900,0,yes,southwest,16884.92400,Young,NaN,0,overweight
1,18,male,33.770,1,no,southeast,1725.55230,Young,NaN,1,overweight
2,28,male,33.000,3,no,southeast,4449.46200,Adult,NaN,1,overweight
3,33,male,22.705,0,no,northwest,21984.47061,Adult,NaN,1,normal
4,32,male,28.880,0,no,northwest,3866.85520,Adult,NaN,1,overweight
...,...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Senior,NaN,1,overweight
1334,18,female,31.920,0,no,northeast,2205.98080,Young,NaN,0,overweight
1335,18,female,36.850,0,no,southeast,1629.83350,Young,NaN,0,overweight
1336,21,female,25.800,0,no,southwest,2007.94500,Young,NaN,0,overweight
1337,61,female,29.070,0,yes,northwest,29141.36030,Senior,NaN,0,overweight

In [39]:
region_encoded=pd.get_dummies(df["region"])
region_encoded

      northeast  northwest  southeast  southwest
0         False      False      False       True
1         False      False       True      False
2         False      False       True      False
3         False       True      False      False
4         False       True      False      False
...         ...        ...        ...        ...
1333      False       True      False      False
1334       True      False      False      False
1335      False      False       True      False
1336      False      False      False       True
1337      False       True      False      False

[1338 rows x 4 columns]

In [41]:

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df["age_scaled"]=scaler.fit_transform(df[["age"]])
df["bmi_scaled"]=scaler.fit_transform(df[["bmi"]])
df["children_scaled"]=scaler.fit_transform(df[["children"]])
df

,age,sex,bmi,children,smoker,region,charges,age_group,smoker_binary,sex_binary,bmi_category,age_scaled,bmi_scaled,children_scaled
0,19,female,27.900,0,yes,southwest,16884.92400,Young,NaN,0,overweight,-1.438764,-0.453320,-0.908614
1,18,male,33.770,1,no,southeast,1725.55230,Young,NaN,1,overweight,-1.509965,0.509621,-0.078767
2,28,male,33.000,3,no,southeast,4449.46200,Adult,NaN,1,overweight,-0.797954,0.383307,1.580926
3,33,male,22.705,0,no,northwest,21984.47061,Adult,NaN,1,normal,-0.441948,-1.305531,-0.908614
4,32,male,28.880,0,no,northwest,3866.85520,Adult,NaN,1,overweight,-0.513149,-0.292556,-0.908614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Senior,NaN,1,overweight,0.768473,0.050297,1.580926
1334,18,female,31.920,0,no,northeast,2205.98080,Young,NaN,0,overweight,-1.509965,0.206139,-0.908614
1335,18,female,36.850,0,no,southeast,1629.83350,Young,NaN,0,overweight,-1.509965,1.014878,-0.908614
1336,21,female,25.800,0,no,southwest,2007.94500,Young,NaN,0,overweight,-1.296362,-0.797813,-0.908614
1337,61,female,29.070,0,yes,northwest,29141.36030,Senior,NaN,0,overweight,1.551686,-0.261388,-0.908614

In [42]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df["age_std"]=scaler.fit_transform(df[["age"]])
df["bmi_std"]=scaler.fit_transform(df[["bmi"]])
df["children_std"]=scaler.fit_transform(df[["children"]])
df

,age,sex,bmi,children,smoker,region,charges,age_group,smoker_binary,sex_binary,bmi_category,age_scaled,bmi_scaled,children_scaled,age_std,bmi_std,children_std
0,19,female,27.900,0,yes,southwest,16884.92400,Young,NaN,0,overweight,-1.438764,-0.453320,-0.908614,-1.438764,-0.453320,-0.908614
1,18,male,33.770,1,no,southeast,1725.55230,Young,NaN,1,overweight,-1.509965,0.509621,-0.078767,-1.509965,0.509621,-0.078767
2,28,male,33.000,3,no,southeast,4449.46200,Adult,NaN,1,overweight,-0.797954,0.383307,1.580926,-0.797954,0.383307,1.580926
3,33,male,22.705,0,no,northwest,21984.47061,Adult,NaN,1,normal,-0.441948,-1.305531,-0.908614,-0.441948,-1.305531,-0.908614
4,32,male,28.880,0,no,northwest,3866.85520,Adult,NaN,1,overweight,-0.513149,-0.292556,-0.908614,-0.513149,-0.292556,-0.908614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Senior,NaN,1,overweight,0.768473,0.050297,1.580926,0.768473,0.050297,1.580926
1334,18,female,31.920,0,no,northeast,2205.98080,Young,NaN,0,overweight,-1.509965,0.206139,-0.908614,-1.509965,0.206139,-0.908614
1335,18,female,36.850,0,no,southeast,1629.83350,Young,NaN,0,overweight,-1.509965,1.014878,-0.908614,-1.509965,1.014878,-0.908614
1336,21,female,25.800,0,no,southwest,2007.94500,Young,NaN,0,overweight,-1.296362,-0.797813,-0.908614,-1.296362,-0.797813,-0.908614
1337,61,female,29.070,0,yes,northwest,29141.36030,Senior,NaN,0,overweight,1.551686,-0.261388,-0.908614,1.551686,-0.261388,-0.908614

In [43]:
df.to_csv("medicalinsurance_feature_enginnering.csv",index=False)

In [44]:
print("Feature engineering abd scalling completed!")

Feature engineering abd scalling completed!